<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class FarmAndLocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        DB::table('geo_paises')->insertOrIgnore([
            [
                'cod_pais' => 840,
                'pais' => 'Estados Unidos - USA',
                'acronimo' => 'USA',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 11:51:16',
            ],
        ]);

        DB::table('geo_departamentos')->insertOrIgnore([
            [
                'cod_pais' => 840,
                'cod_departamento' => 1,
                'departamento' => 'Alabama (AL)',
                'acronimo' => 'AL',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:38',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 2,
                'departamento' => 'Alaska (AK)',
                'acronimo' => 'AK',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:38',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 3,
                'departamento' => 'Arizona (AZ)',
                'acronimo' => 'AZ',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:39',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 4,
                'departamento' => 'Arkansas (AR)',
                'acronimo' => 'AR',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:39',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 5,
                'departamento' => 'California (CA)',
                'acronimo' => 'CA',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:39',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 6,
                'departamento' => 'Colorado (CO)',
                'acronimo' => 'CO',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:39',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 7,
                'departamento' => 'Conneticut (CT)',
                'acronimo' => 'CT',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:39',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 8,
                'departamento' => 'Deleware (DE)',
                'acronimo' => 'DE',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:39',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 9,
                'departamento' => 'District of Columbia (DC)',
                'acronimo' => 'DC',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:40',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 10,
                'departamento' => 'Florida (FL)',
                'acronimo' => 'FL',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:40',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 11,
                'departamento' => 'Georgia (GA)',
                'acronimo' => 'GA',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:40',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 12,
                'departamento' => 'Hawaii (HI)',
                'acronimo' => 'HI',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:40',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 13,
                'departamento' => 'Idaho (ID)',
                'acronimo' => 'ID',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:40',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 14,
                'departamento' => 'Illinois (IL)',
                'acronimo' => 'IL',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:40',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 15,
                'departamento' => 'Indiana (IN)',
                'acronimo' => 'IN',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:41',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 16,
                'departamento' => 'Iowa (IA)',
                'acronimo' => 'IA',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:41',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 17,
                'departamento' => 'Kansas (KS)',
                'acronimo' => 'KS',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:41',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 18,
                'departamento' => 'Kentucky (KY)',
                'acronimo' => 'KY',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:41',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 19,
                'departamento' => 'Lousiana (LA)',
                'acronimo' => 'LA',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:41',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 20,
                'departamento' => 'Maine (ME)',
                'acronimo' => 'ME',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:41',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 21,
                'departamento' => 'Maryland (MD)',
                'acronimo' => 'MD',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:42',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 22,
                'departamento' => 'Massachusetts (MA)',
                'acronimo' => 'MA',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:42',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 23,
                'departamento' => 'Michigan (MI)',
                'acronimo' => 'MI',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:42',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 24,
                'departamento' => 'Minnesota (MN)',
                'acronimo' => 'MN',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:42',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 25,
                'departamento' => 'Mississippo (MS)',
                'acronimo' => 'MS',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:42',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 26,
                'departamento' => 'Missouri (MO)',
                'acronimo' => 'MO',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:42',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 27,
                'departamento' => 'Montana (MT)',
                'acronimo' => 'MT',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:43',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 28,
                'departamento' => 'Nebraska (NE)',
                'acronimo' => 'NE',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:43',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 29,
                'departamento' => 'Nevada (NV)',
                'acronimo' => 'NV',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:43',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 30,
                'departamento' => 'New Hampshire (NH)',
                'acronimo' => 'NH',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:43',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 31,
                'departamento' => 'New Jersey (NJ)',
                'acronimo' => 'NJ',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:43',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 32,
                'departamento' => 'New Mexico (NM)',
                'acronimo' => 'NM',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:43',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 33,
                'departamento' => 'New York (NY)',
                'acronimo' => 'NY',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:43',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 34,
                'departamento' => 'North Carolina (NC)',
                'acronimo' => 'NC',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:44',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 35,
                'departamento' => 'North Dakota (ND)',
                'acronimo' => 'ND',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:44',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 36,
                'departamento' => 'Ohio (OH)',
                'acronimo' => 'OH',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:44',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 37,
                'departamento' => 'Oklahoma (OK)',
                'acronimo' => 'OK',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:44',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 38,
                'departamento' => 'Oregon (OR)',
                'acronimo' => 'OR',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:44',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 39,
                'departamento' => 'Pennsylvania (PA)',
                'acronimo' => 'PA',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:44',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 40,
                'departamento' => 'Rhode Island (RI)',
                'acronimo' => 'RI',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:45',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 41,
                'departamento' => 'South Carolina (SC)',
                'acronimo' => 'SC',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:45',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 42,
                'departamento' => 'South Dakota (SD)',
                'acronimo' => 'SD',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:45',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 43,
                'departamento' => 'Tennessee (TN)',
                'acronimo' => 'TN',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:45',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 44,
                'departamento' => 'Texas (TX)',
                'acronimo' => 'YX',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:45',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 45,
                'departamento' => 'Utah (UT)',
                'acronimo' => 'UT',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:45',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 46,
                'departamento' => 'Vermont (VT)',
                'acronimo' => 'VT',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:46',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 47,
                'departamento' => 'Virginia (VA)',
                'acronimo' => 'VA',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:46',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 48,
                'departamento' => 'Washington (WA)',
                'acronimo' => 'WA',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:46',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 49,
                'departamento' => 'West Virginia (WV)',
                'acronimo' => 'WV',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:46',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 50,
                'departamento' => 'Wisconsin (WI)',
                'acronimo' => 'WI',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:46',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 51,
                'departamento' => 'Wyoming (WY)',
                'acronimo' => 'WY',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 12:08:46',
            ],
        ]);

        DB::table('geo_municipios')->insertOrIgnore([
            [
                'cod_pais' => 840,
                'cod_departamento' => 1,
                'cod_municipio' => 1,
                'municipio' => 'Alabama (AL)',
                'acronimo' => 'AL',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:32',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 2,
                'cod_municipio' => 2,
                'municipio' => 'Alaska (AK)',
                'acronimo' => 'AK',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:32',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 3,
                'cod_municipio' => 3,
                'municipio' => 'Arizona (AZ)',
                'acronimo' => 'AZ',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:32',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 4,
                'cod_municipio' => 4,
                'municipio' => 'Arkansas (AR)',
                'acronimo' => 'AR',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:33',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 5,
                'cod_municipio' => 5,
                'municipio' => 'California (CA)',
                'acronimo' => 'CA',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:33',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 6,
                'cod_municipio' => 6,
                'municipio' => 'Colorado (CO)',
                'acronimo' => 'CO',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:33',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 7,
                'cod_municipio' => 7,
                'municipio' => 'Conneticut (CT)',
                'acronimo' => 'CT',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:33',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 8,
                'cod_municipio' => 8,
                'municipio' => 'Deleware (DE)',
                'acronimo' => 'DE',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:33',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 9,
                'cod_municipio' => 9,
                'municipio' => 'District of Columbia (DC)',
                'acronimo' => 'DC',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:33',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 10,
                'cod_municipio' => 10,
                'municipio' => 'Florida (FL)',
                'acronimo' => 'FL',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:34',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 11,
                'cod_municipio' => 11,
                'municipio' => 'Georgia (GA)',
                'acronimo' => 'GA',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:34',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 12,
                'cod_municipio' => 12,
                'municipio' => 'Hawaii (HI)',
                'acronimo' => 'HI',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:34',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 13,
                'cod_municipio' => 13,
                'municipio' => 'Idaho (ID)',
                'acronimo' => 'ID',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:34',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 14,
                'cod_municipio' => 14,
                'municipio' => 'Illinois (IL)',
                'acronimo' => 'IL',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:34',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 15,
                'cod_municipio' => 15,
                'municipio' => 'Indiana (IN)',
                'acronimo' => 'IN',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:34',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 16,
                'cod_municipio' => 16,
                'municipio' => 'Iowa (IA)',
                'acronimo' => 'IA',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:35',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 17,
                'cod_municipio' => 17,
                'municipio' => 'Kansas (KS)',
                'acronimo' => 'KS',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:35',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 18,
                'cod_municipio' => 18,
                'municipio' => 'Kentucky (KY)',
                'acronimo' => 'KY',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:36',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 19,
                'cod_municipio' => 19,
                'municipio' => 'Lousiana (LA)',
                'acronimo' => 'LA',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:36',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 20,
                'cod_municipio' => 20,
                'municipio' => 'Maine (ME)',
                'acronimo' => 'ME',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:37',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 21,
                'cod_municipio' => 21,
                'municipio' => 'Maryland (MD)',
                'acronimo' => 'MD',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:37',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 22,
                'cod_municipio' => 22,
                'municipio' => 'Massachusetts (MA)',
                'acronimo' => 'MA',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:37',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 23,
                'cod_municipio' => 23,
                'municipio' => 'Michigan (MI)',
                'acronimo' => 'MI',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:39',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 24,
                'cod_municipio' => 24,
                'municipio' => 'Minnesota (MN)',
                'acronimo' => 'MN',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:39',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 25,
                'cod_municipio' => 25,
                'municipio' => 'Mississippo (MS)',
                'acronimo' => 'MS',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:39',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 26,
                'cod_municipio' => 26,
                'municipio' => 'Missouri (MO)',
                'acronimo' => 'MO',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:39',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 27,
                'cod_municipio' => 27,
                'municipio' => 'Montana (MT)',
                'acronimo' => 'MT',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:39',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 28,
                'cod_municipio' => 28,
                'municipio' => 'Nebraska (NE)',
                'acronimo' => 'NE',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:40',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 29,
                'cod_municipio' => 29,
                'municipio' => 'Nevada (NV)',
                'acronimo' => 'NV',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:40',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 30,
                'cod_municipio' => 30,
                'municipio' => 'New Hampshire (NH)',
                'acronimo' => 'NH',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:40',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 31,
                'cod_municipio' => 31,
                'municipio' => 'New Jersey (NJ)',
                'acronimo' => 'NJ',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:40',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 32,
                'cod_municipio' => 32,
                'municipio' => 'New Mexico (NM)',
                'acronimo' => 'NM',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:40',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 33,
                'cod_municipio' => 33,
                'municipio' => 'New York (NY)',
                'acronimo' => 'NY',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:40',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 34,
                'cod_municipio' => 34,
                'municipio' => 'North Carolina (NC)',
                'acronimo' => 'NC',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:41',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 35,
                'cod_municipio' => 35,
                'municipio' => 'North Dakota (ND)',
                'acronimo' => 'ND',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:41',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 36,
                'cod_municipio' => 36,
                'municipio' => 'Ohio (OH)',
                'acronimo' => 'OH',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:41',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 37,
                'cod_municipio' => 37,
                'municipio' => 'Oklahoma (OK)',
                'acronimo' => 'OK',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:41',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 38,
                'cod_municipio' => 38,
                'municipio' => 'Oregon (OR)',
                'acronimo' => 'OR',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:41',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 39,
                'cod_municipio' => 39,
                'municipio' => 'Pennsylvania (PA)',
                'acronimo' => 'PA',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:41',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 40,
                'cod_municipio' => 40,
                'municipio' => 'Rhode Island (RI)',
                'acronimo' => 'RI',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:41',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 41,
                'cod_municipio' => 41,
                'municipio' => 'South Carolina (SC)',
                'acronimo' => 'SC',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:42',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 42,
                'cod_municipio' => 42,
                'municipio' => 'South Dakota (SD)',
                'acronimo' => 'SD',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:42',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 43,
                'cod_municipio' => 43,
                'municipio' => 'Tennessee (TN)',
                'acronimo' => 'TN',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:42',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 44,
                'cod_municipio' => 44,
                'municipio' => 'Texas (TX)',
                'acronimo' => 'YX',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:42',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 45,
                'cod_municipio' => 45,
                'municipio' => 'Utah (UT)',
                'acronimo' => 'UT',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:42',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 46,
                'cod_municipio' => 46,
                'municipio' => 'Vermont (VT)',
                'acronimo' => 'VT',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:42',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 47,
                'cod_municipio' => 47,
                'municipio' => 'Virginia (VA)',
                'acronimo' => 'VA',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:42',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 48,
                'cod_municipio' => 48,
                'municipio' => 'Washington (WA)',
                'acronimo' => 'WA',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:43',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 49,
                'cod_municipio' => 49,
                'municipio' => 'West Virginia (WV)',
                'acronimo' => 'WV',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:43',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 50,
                'cod_municipio' => 50,
                'municipio' => 'Wisconsin (WI)',
                'acronimo' => 'WI',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:43',
            ],
            [
                'cod_pais' => 840,
                'cod_departamento' => 51,
                'cod_municipio' => 51,
                'municipio' => 'Wyoming (WY)',
                'acronimo' => 'WY',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-26 14:18:43',
            ],
        ]);

        DB::table('far_temporadas')->insertOrIgnore([
            [
                'cod_temporada' => 1,
                'temporada' => '2023-2024',
                'nota' => 'Prueba desde Postman',
                'activo' => 0,
                'user_insert' => 1,
                'date_insert' => '2024-02-18 20:07:03',
            ],
            [
                'cod_temporada' => 7,
                'temporada' => 'Temporada #2',
                'nota' => 'Registro de prueba',
                'activo' => 0,
                'user_insert' => 1,
                'date_insert' => '2024-02-25 11:47:29',
            ],
            [
                'cod_temporada' => 8,
                'temporada' => 'Temporada #3',
                'nota' => 'Cambio de estado',
                'activo' => 0,
                'user_insert' => 1,
                'date_insert' => '2024-02-25 11:53:05',
            ],
            [
                'cod_temporada' => 9,
                'temporada' => 'Temporada #4',
                'nota' => 'dfdfdfd',
                'activo' => 0,
                'user_insert' => 1,
                'date_insert' => '2024-02-25 11:55:07',
            ],
            [
                'cod_temporada' => 10,
                'temporada' => '2023-2024',
                'nota' => 'FL (2023-24), GA (2024), PA (2024)',
                'activo' => 0,
                'user_insert' => 3,
                'date_insert' => '2024-04-30 04:33:33',
            ],
            [
                'cod_temporada' => 11,
                'temporada' => '2024-2025',
                'nota' => 'FL (2024-25)',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-04 08:09:52',
            ],
        ]);

        DB::table('far_farms')->insertOrIgnore([
            [
                'cod_farms' => 1,
                'cod_estado' => 2,
                'farm' => 'Punta Gorda',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-02-25 14:03:39',
            ],
            [
                'cod_farms' => 2,
                'cod_estado' => 2,
                'farm' => 'Babcock',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-02-25 16:13:16',
            ],
            [
                'cod_farms' => 3,
                'cod_estado' => 1,
                'farm' => 'Cool Spring',
                'activo' => 0,
                'user_insert' => 1,
                'date_insert' => '2024-02-25 16:13:45',
            ],
            [
                'cod_farms' => 4,
                'cod_estado' => 3,
                'farm' => 'St. Thomas',
                'activo' => 0,
                'user_insert' => 1,
                'date_insert' => '2024-02-25 16:13:45',
            ],
            [
                'cod_farms' => 5,
                'cod_estado' => 3,
                'farm' => 'Mercerburg',
                'activo' => 0,
                'user_insert' => 1,
                'date_insert' => '2024-03-01 13:07:42',
            ],
            [
                'cod_farms' => 6,
                'cod_estado' => 3,
                'farm' => 'Peckman',
                'activo' => 0,
                'user_insert' => 3,
                'date_insert' => '2024-04-29 13:27:24',
            ],
        ]);

        DB::table('far_locations')->insertOrIgnore([
            [
                'cod_location' => 1,
                'cod_farms' => 1,
                'location' => 'Field-Campo',
                'abreviacion' => 'Field',
                'cost_center' => '01120',
                'labor_phase' => '22615',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-07-15 12:56:19',
            ],
            [
                'cod_location' => 2,
                'cod_farms' => 1,
                'location' => 'Packing House-Empaque',
                'abreviacion' => 'Packhouse',
                'cost_center' => '01100',
                'labor_phase' => '22610',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-07-15 12:56:19',
            ],
            [
                'cod_location' => 3,
                'cod_farms' => 1,
                'location' => 'Shop-Taller',
                'abreviacion' => 'Shop',
                'cost_center' => '01120',
                'labor_phase' => '22615',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-08-06 22:30:56',
            ],
            [
                'cod_location' => 4,
                'cod_farms' => 2,
                'location' => 'Field-Campo',
                'abreviacion' => 'Field',
                'cost_center' => '01130',
                'labor_phase' => '22615',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-09-04 22:24:46',
            ],
            [
                'cod_location' => 7,
                'cod_farms' => 4,
                'location' => 'Field-Campo',
                'abreviacion' => 'F',
                'cost_center' => '0',
                'labor_phase' => '0',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-09-04 22:24:46',
            ],
            [
                'cod_location' => 8,
                'cod_farms' => 4,
                'location' => 'Packing House',
                'abreviacion' => 'PH',
                'cost_center' => '0',
                'labor_phase' => '0',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-09-04 22:24:46',
            ],
            [
                'cod_location' => 9,
                'cod_farms' => 4,
                'location' => 'Shop',
                'abreviacion' => 'S',
                'cost_center' => '0',
                'labor_phase' => '0',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-09-04 22:24:46',
            ],
            [
                'cod_location' => 10,
                'cod_farms' => 5,
                'location' => 'Field-Campo',
                'abreviacion' => 'F',
                'cost_center' => '0',
                'labor_phase' => '0',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-09-04 22:24:46',
            ],
            [
                'cod_location' => 13,
                'cod_farms' => 6,
                'location' => 'Field-Campo',
                'abreviacion' => 'F',
                'cost_center' => '0',
                'labor_phase' => '0',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-09-04 22:24:46',
            ],
            [
                'cod_location' => 16,
                'cod_farms' => 1,
                'location' => 'Office-Oficina',
                'abreviacion' => 'Office',
                'cost_center' => '01100',
                'labor_phase' => '22625',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-09-04 22:24:46',
            ],
            [
                'cod_location' => 17,
                'cod_farms' => 4,
                'location' => 'Office',
                'abreviacion' => 'O',
                'cost_center' => '0',
                'labor_phase' => '0',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-09-04 22:24:46',
            ],
        ]);

        DB::table('far_fields')->insertOrIgnore([
            [
                'cod_field' => 1,
                'cod_farm' => 1,
                'field' => 'A 1',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-02-25 22:23:53',
            ],
            [
                'cod_field' => 2,
                'cod_farm' => 1,
                'field' => 'A 2-3',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-02-25 23:00:37',
            ],
            [
                'cod_field' => 3,
                'cod_farm' => 1,
                'field' => 'A 4-5',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-02-25 23:00:37',
            ],
            [
                'cod_field' => 4,
                'cod_farm' => 1,
                'field' => 'A 6-7',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-02-25 23:00:37',
            ],
            [
                'cod_field' => 5,
                'cod_farm' => 1,
                'field' => 'A 8',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-02-25 23:00:37',
            ],
            [
                'cod_field' => 6,
                'cod_farm' => 1,
                'field' => 'A 9-10',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:11:31',
            ],
            [
                'cod_field' => 7,
                'cod_farm' => 1,
                'field' => 'B 1',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:13:43',
            ],
            [
                'cod_field' => 8,
                'cod_farm' => 1,
                'field' => 'B 2-3',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:18:35',
            ],
            [
                'cod_field' => 9,
                'cod_farm' => 1,
                'field' => 'B 4-5',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:18:35',
            ],
            [
                'cod_field' => 10,
                'cod_farm' => 1,
                'field' => 'B 6-7',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:18:35',
            ],
            [
                'cod_field' => 11,
                'cod_farm' => 1,
                'field' => 'C 1-2',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:18:35',
            ],
            [
                'cod_field' => 12,
                'cod_farm' => 1,
                'field' => 'C 3-4',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:18:35',
            ],
            [
                'cod_field' => 13,
                'cod_farm' => 1,
                'field' => 'E 1-2',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:18:35',
            ],
            [
                'cod_field' => 14,
                'cod_farm' => 2,
                'field' => '1',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:31:01',
            ],
            [
                'cod_field' => 15,
                'cod_farm' => 2,
                'field' => '2',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:31:01',
            ],
            [
                'cod_field' => 16,
                'cod_farm' => 2,
                'field' => '3',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:31:01',
            ],
            [
                'cod_field' => 17,
                'cod_farm' => 2,
                'field' => '4',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:31:01',
            ],
            [
                'cod_field' => 18,
                'cod_farm' => 2,
                'field' => '5',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:31:01',
            ],
            [
                'cod_field' => 19,
                'cod_farm' => 2,
                'field' => '6',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:31:01',
            ],
            [
                'cod_field' => 20,
                'cod_farm' => 2,
                'field' => '7',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:31:01',
            ],
            [
                'cod_field' => 21,
                'cod_farm' => 2,
                'field' => '8',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:31:02',
            ],
            [
                'cod_field' => 22,
                'cod_farm' => 3,
                'field' => 'A 1',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:31:04',
            ],
            [
                'cod_field' => 23,
                'cod_farm' => 3,
                'field' => 'A 2',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:31:04',
            ],
            [
                'cod_field' => 24,
                'cod_farm' => 3,
                'field' => 'B 1',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:31:05',
            ],
            [
                'cod_field' => 25,
                'cod_farm' => 3,
                'field' => 'B 2',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:31:05',
            ],
            [
                'cod_field' => 26,
                'cod_farm' => 3,
                'field' => 'B 3',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:31:05',
            ],
            [
                'cod_field' => 27,
                'cod_farm' => 3,
                'field' => 'B 4',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:31:05',
            ],
            [
                'cod_field' => 28,
                'cod_farm' => 3,
                'field' => 'B 5',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:31:05',
            ],
            [
                'cod_field' => 29,
                'cod_farm' => 3,
                'field' => 'B 6',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:31:05',
            ],
            [
                'cod_field' => 30,
                'cod_farm' => 3,
                'field' => 'C 1',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:57:03',
            ],
            [
                'cod_field' => 31,
                'cod_farm' => 3,
                'field' => 'C 2',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 16:57:03',
            ],
            [
                'cod_field' => 32,
                'cod_farm' => 4,
                'field' => '1',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:04:51',
            ],
            [
                'cod_field' => 33,
                'cod_farm' => 4,
                'field' => '2',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:04:51',
            ],
            [
                'cod_field' => 34,
                'cod_farm' => 4,
                'field' => '3',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:04:51',
            ],
            [
                'cod_field' => 35,
                'cod_farm' => 4,
                'field' => '4',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:04:51',
            ],
            [
                'cod_field' => 36,
                'cod_farm' => 4,
                'field' => '5',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:04:51',
            ],
            [
                'cod_field' => 37,
                'cod_farm' => 4,
                'field' => '6',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:04:52',
            ],
            [
                'cod_field' => 38,
                'cod_farm' => 4,
                'field' => '7',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:04:52',
            ],
            [
                'cod_field' => 39,
                'cod_farm' => 4,
                'field' => '8',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:04:52',
            ],
            [
                'cod_field' => 40,
                'cod_farm' => 4,
                'field' => '9',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:04:52',
            ],
            [
                'cod_field' => 41,
                'cod_farm' => 4,
                'field' => '9-1',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:04:53',
            ],
            [
                'cod_field' => 42,
                'cod_farm' => 4,
                'field' => '10',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:04:53',
            ],
            [
                'cod_field' => 43,
                'cod_farm' => 4,
                'field' => '11',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:04:54',
            ],
            [
                'cod_field' => 44,
                'cod_farm' => 4,
                'field' => 'CPGD 1',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:04:54',
            ],
            [
                'cod_field' => 45,
                'cod_farm' => 4,
                'field' => 'CPGD 2',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:04:54',
            ],
            [
                'cod_field' => 46,
                'cod_farm' => 4,
                'field' => 'CPGD 3',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:04:54',
            ],
            [
                'cod_field' => 47,
                'cod_farm' => 5,
                'field' => '1',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:13:12',
            ],
            [
                'cod_field' => 48,
                'cod_farm' => 5,
                'field' => '2',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:13:12',
            ],
            [
                'cod_field' => 49,
                'cod_farm' => 5,
                'field' => '3',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:13:12',
            ],
            [
                'cod_field' => 50,
                'cod_farm' => 5,
                'field' => '4',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-03-01 17:13:12',
            ],
            [
                'cod_field' => 51,
                'cod_farm' => 6,
                'field' => '1',
                'activo' => '1',
                'user_insert' => 3,
                'date_insert' => '2024-06-11 09:14:04',
            ],
            [
                'cod_field' => 52,
                'cod_farm' => 6,
                'field' => '2',
                'activo' => '1',
                'user_insert' => 3,
                'date_insert' => '2024-06-11 09:14:17',
            ],
        ]);

        Schema::enableForeignKeyConstraints();
    }
}
