<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PayrollCatalogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        DB::table('pay_estados_jobs')->insertOrIgnore([
            [
                'cod_estado_job' => 1,
                'estado_job' => 'lista',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-07-22 00:48:03',
            ],
            [
                'cod_estado_job' => 2,
                'estado_job' => 'iniciada',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-07-22 00:48:03',
            ],
            [
                'cod_estado_job' => 3,
                'estado_job' => 'culminada',
                'activo' => '1',
                'user_insert' => 1,
                'date_insert' => '2024-07-22 00:48:03',
            ],
        ]);

        DB::table('pay_tipo_pagos')->insertOrIgnore([
            [
                'cod_tipo_pago' => 1,
                'tipo_pago' => 'Hours',
                'abreviatura' => 'HR',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-06-21 22:06:08',
            ],
            [
                'cod_tipo_pago' => 2,
                'tipo_pago' => 'Pieces',
                'abreviatura' => 'PR',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-06-21 22:06:08',
            ],
        ]);

        DB::table('pay_tipo_packs')->insertOrIgnore([
            [
                'cod_tipo_pack' => 2,
                'tipo_pack' => 'Bucket',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-09-29 21:38:55',
            ],
            [
                'cod_tipo_pack' => 3,
                'tipo_pack' => 'Bucket',
                'cantidad' => 1,
                'piece_rate' => '0.27',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 06:05:03',
            ],
            [
                'cod_tipo_pack' => 4,
                'tipo_pack' => '30#',
                'cantidad' => 1,
                'piece_rate' => '0.15',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 06:05:50',
            ],
            [
                'cod_tipo_pack' => 5,
                'tipo_pack' => '20#',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 06:06:21',
            ],
            [
                'cod_tipo_pack' => 10,
                'tipo_pack' => '24 Count',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 06:09:47',
            ],
            [
                'cod_tipo_pack' => 11,
                'tipo_pack' => '30 Count',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 06:11:23',
            ],
            [
                'cod_tipo_pack' => 12,
                'tipo_pack' => '12 Count',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 06:12:44',
            ],
            [
                'cod_tipo_pack' => 13,
                'tipo_pack' => '20# Bulk',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 06:16:11',
            ],
            [
                'cod_tipo_pack' => 14,
                'tipo_pack' => 'Desojado-De-stemmed',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 06:17:15',
            ],
            [
                'cod_tipo_pack' => 15,
                'tipo_pack' => '36 Hearts',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 06:17:40',
            ],
            [
                'cod_tipo_pack' => 16,
                'tipo_pack' => '15 Count',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 06:18:07',
            ],
            [
                'cod_tipo_pack' => 17,
                'tipo_pack' => '30#',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-09-30 08:15:41',
            ],
            [
                'cod_tipo_pack' => 18,
                'tipo_pack' => '20#',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 08:34:07',
            ],
            [
                'cod_tipo_pack' => 19,
                'tipo_pack' => '24 Count',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 08:35:45',
            ],
            [
                'cod_tipo_pack' => 20,
                'tipo_pack' => '30 Count',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 08:36:26',
            ],
            [
                'cod_tipo_pack' => 21,
                'tipo_pack' => '12 Count',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 08:38:10',
            ],
            [
                'cod_tipo_pack' => 22,
                'tipo_pack' => '20# Bulk',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 08:39:22',
            ],
            [
                'cod_tipo_pack' => 23,
                'tipo_pack' => 'Desojado-De-stemmed',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 08:40:29',
            ],
            [
                'cod_tipo_pack' => 24,
                'tipo_pack' => '36 Hearts',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 08:40:59',
            ],
            [
                'cod_tipo_pack' => 25,
                'tipo_pack' => '15 Count',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 08:41:24',
            ],
            [
                'cod_tipo_pack' => 26,
                'tipo_pack' => '30 Count',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 08:42:41',
            ],
            [
                'cod_tipo_pack' => 27,
                'tipo_pack' => '30 Count',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 08:42:59',
            ],
            [
                'cod_tipo_pack' => 28,
                'tipo_pack' => '45#',
                'cantidad' => 1,
                'piece_rate' => '0.01',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-15 18:02:15',
            ],
            [
                'cod_tipo_pack' => 29,
                'tipo_pack' => '20# Bagged',
                'cantidad' => 1,
                'piece_rate' => '0.01',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-15 18:05:07',
            ],
            [
                'cod_tipo_pack' => 30,
                'tipo_pack' => '45#',
                'cantidad' => 1,
                'piece_rate' => '0.01',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-15 18:05:33',
            ],
            [
                'cod_tipo_pack' => 31,
                'tipo_pack' => '20# Bagged',
                'cantidad' => 1,
                'piece_rate' => '0.01',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-15 18:06:05',
            ],
            [
                'cod_tipo_pack' => 32,
                'tipo_pack' => '20# Crowns',
                'cantidad' => 1,
                'piece_rate' => '0.01',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-21 11:37:46',
            ],
            [
                'cod_tipo_pack' => 33,
                'tipo_pack' => '20# Crowns',
                'cantidad' => 1,
                'piece_rate' => '0.01',
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-21 11:38:08',
            ],
            [
                'cod_tipo_pack' => 34,
                'tipo_pack' => '20#',
                'cantidad' => 1,
                'piece_rate' => '0.00',
                'activo' => 5,
                'user_insert' => 1,
                'date_insert' => '2024-11-22 00:17:33',
            ],
        ]);

        DB::table('pay_activities')->insertOrIgnore([
            [
                'cod_activity' => 1,
                'cod_farms' => 1,
                'cod_location' => 1,
                'codigo' => '1',
                'activity' => 'Prepare for Planting-Preparar para plantar',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-09-30 08:25:34',
            ],
            [
                'cod_activity' => 2,
                'cod_farms' => 1,
                'cod_location' => 1,
                'codigo' => '2',
                'activity' => 'Laying Plastic-Tirar Plastico',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 13:05:48',
            ],
            [
                'cod_activity' => 3,
                'cod_farms' => 1,
                'cod_location' => 1,
                'codigo' => '3',
                'activity' => 'Spraying-Esprayar',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 13:06:07',
            ],
            [
                'cod_activity' => 4,
                'cod_farms' => 1,
                'cod_location' => 1,
                'codigo' => '4',
                'activity' => 'Rototilling-Calabera',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 13:06:26',
            ],
            [
                'cod_activity' => 5,
                'cod_farms' => 1,
                'cod_location' => 1,
                'codigo' => '5',
                'activity' => 'Planting-Plantando',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 13:06:45',
            ],
            [
                'cod_activity' => 6,
                'cod_farms' => 2,
                'cod_location' => 4,
                'codigo' => '2',
                'activity' => 'Laying Plastic-Tirar Plastico',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 13:07:00',
            ],
            [
                'cod_activity' => 7,
                'cod_farms' => 1,
                'cod_location' => 1,
                'codigo' => '7',
                'activity' => 'Tying-Amarrar',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 13:07:40',
            ],
            [
                'cod_activity' => 8,
                'cod_farms' => 1,
                'cod_location' => 1,
                'codigo' => '8',
                'activity' => 'Hand Weeding-Deshierbar a mano',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 13:07:58',
            ],
            [
                'cod_activity' => 9,
                'cod_farms' => 1,
                'cod_location' => 1,
                'codigo' => '9',
                'activity' => 'Water Wagon-Guaina',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 13:08:21',
            ],
            [
                'cod_activity' => 10,
                'cod_farms' => 1,
                'cod_location' => 1,
                'codigo' => '10',
                'activity' => 'Irrigation-Riego',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 13:08:44',
            ],
            [
                'cod_activity' => 11,
                'cod_farms' => 1,
                'cod_location' => 1,
                'codigo' => '11',
                'activity' => 'Mowing-Morrear',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 13:09:00',
            ],
            [
                'cod_activity' => 12,
                'cod_farms' => 1,
                'cod_location' => 1,
                'codigo' => '12',
                'activity' => 'Cleaning Field-Limpear campo',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 13:09:21',
            ],
            [
                'cod_activity' => 13,
                'cod_farms' => 1,
                'cod_location' => 1,
                'codigo' => '13',
                'activity' => 'Sowing Seed-Sembrar semila',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 13:09:39',
            ],
            [
                'cod_activity' => 14,
                'cod_farms' => 1,
                'cod_location' => 1,
                'codigo' => '14',
                'activity' => 'Pruning-Deshijar',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 13:10:03',
            ],
            [
                'cod_activity' => 15,
                'cod_farms' => 1,
                'cod_location' => 1,
                'codigo' => '15',
                'activity' => 'Greenhouse Work-Invernadero',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 13:10:25',
            ],
            [
                'cod_activity' => 16,
                'cod_farms' => 1,
                'cod_location' => 1,
                'codigo' => '16',
                'activity' => 'Planting Cover Crop-Cultivo de cobertura',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 13:10:51',
            ],
            [
                'cod_activity' => 17,
                'cod_farms' => 1,
                'cod_location' => 16,
                'codigo' => '1',
                'activity' => 'General Work',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 13:11:16',
            ],
            [
                'cod_activity' => 18,
                'cod_farms' => 4,
                'cod_location' => 9,
                'codigo' => '1',
                'activity' => 'General Work',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-09-30 13:11:42',
            ],
            [
                'cod_activity' => 19,
                'cod_farms' => 1,
                'cod_location' => 1,
                'codigo' => '17',
                'activity' => 'Staking-Estaquiado',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-02 12:28:43',
            ],
            [
                'cod_activity' => 20,
                'cod_farms' => 2,
                'cod_location' => 4,
                'codigo' => '1',
                'activity' => 'Prepare for Planting-Preparar para plantar',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:09:42',
            ],
            [
                'cod_activity' => 21,
                'cod_farms' => 2,
                'cod_location' => 4,
                'codigo' => '3',
                'activity' => 'Spraying-Esprayar',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:10:25',
            ],
            [
                'cod_activity' => 22,
                'cod_farms' => 2,
                'cod_location' => 4,
                'codigo' => '4',
                'activity' => 'Rototilling-Calabera',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:10:41',
            ],
            [
                'cod_activity' => 23,
                'cod_farms' => 2,
                'cod_location' => 4,
                'codigo' => '5',
                'activity' => 'Planting-Plantado',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:10:55',
            ],
            [
                'cod_activity' => 24,
                'cod_farms' => 2,
                'cod_location' => 4,
                'codigo' => '7',
                'activity' => 'Tying-Amarrar',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:13:00',
            ],
            [
                'cod_activity' => 25,
                'cod_farms' => 2,
                'cod_location' => 4,
                'codigo' => '8',
                'activity' => 'Hand Weeding-Deshierbar a mano',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:13:13',
            ],
            [
                'cod_activity' => 26,
                'cod_farms' => 2,
                'cod_location' => 4,
                'codigo' => '9',
                'activity' => 'Water Wagon-Guaina',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:13:29',
            ],
            [
                'cod_activity' => 27,
                'cod_farms' => 2,
                'cod_location' => 4,
                'codigo' => '10',
                'activity' => 'Irrigation-Riego',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:13:53',
            ],
            [
                'cod_activity' => 28,
                'cod_farms' => 2,
                'cod_location' => 4,
                'codigo' => '11',
                'activity' => 'Mowing-Morrear',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:14:07',
            ],
            [
                'cod_activity' => 29,
                'cod_farms' => 2,
                'cod_location' => 4,
                'codigo' => '12',
                'activity' => 'Cleaning Field-Limpiar campo',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:14:31',
            ],
            [
                'cod_activity' => 30,
                'cod_farms' => 2,
                'cod_location' => 4,
                'codigo' => '13',
                'activity' => 'Sowing Seed-Sembrar Semilla',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:14:53',
            ],
            [
                'cod_activity' => 31,
                'cod_farms' => 2,
                'cod_location' => 4,
                'codigo' => '14',
                'activity' => 'Pruning-Deshijar',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:15:12',
            ],
            [
                'cod_activity' => 32,
                'cod_farms' => 2,
                'cod_location' => 4,
                'codigo' => '15',
                'activity' => 'Greenhouse Work-Invernadero',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:15:26',
            ],
            [
                'cod_activity' => 33,
                'cod_farms' => 2,
                'cod_location' => 4,
                'codigo' => '16',
                'activity' => 'Planting Cover Crop-Cultivo de cobertura',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:15:50',
            ],
            [
                'cod_activity' => 34,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '1',
                'activity' => 'Heirlooms',
                'piece_rate' => '0.01',
                'activo' => 0,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:17:49',
            ],
            [
                'cod_activity' => 35,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '2',
                'activity' => 'Grapes',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:18:08',
            ],
            [
                'cod_activity' => 36,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '3',
                'activity' => 'Grapes Open Pints',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:18:29',
            ],
            [
                'cod_activity' => 37,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '4',
                'activity' => 'Grapes 1# Clams',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:18:46',
            ],
            [
                'cod_activity' => 38,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '5',
                'activity' => 'Bulk Grapes',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:19:05',
            ],
            [
                'cod_activity' => 39,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '6',
                'activity' => 'ECO Grapes',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:19:24',
            ],
            [
                'cod_activity' => 40,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '7',
                'activity' => 'Cherries',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:19:40',
            ],
            [
                'cod_activity' => 41,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '8',
                'activity' => 'Cherries Open Pints',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:20:48',
            ],
            [
                'cod_activity' => 42,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '9',
                'activity' => 'Medley Mix',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:22:08',
            ],
            [
                'cod_activity' => 43,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '10',
                'activity' => 'Medley Mix Open 12 Ct',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:22:29',
            ],
            [
                'cod_activity' => 44,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '11',
                'activity' => 'Gold Grapes',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:22:44',
            ],
            [
                'cod_activity' => 45,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '12',
                'activity' => 'Sun Gold Cherries',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:22:59',
            ],
            [
                'cod_activity' => 46,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '13',
                'activity' => 'Sun Gold Open Pints',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:23:20',
            ],
            [
                'cod_activity' => 47,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '14',
                'activity' => 'Sun Peach Open Pints',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:23:36',
            ],
            [
                'cod_activity' => 48,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '15',
                'activity' => 'Eggplant',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:23:55',
            ],
            [
                'cod_activity' => 49,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '16',
                'activity' => 'ECO Eggplant',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:24:15',
            ],
            [
                'cod_activity' => 50,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '17',
                'activity' => 'Jalapenos',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:24:32',
            ],
            [
                'cod_activity' => 51,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '18',
                'activity' => 'Snack Peppers',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:24:51',
            ],
            [
                'cod_activity' => 52,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '19',
                'activity' => 'Shishito Peppers-Bags',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:25:11',
            ],
            [
                'cod_activity' => 53,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '20',
                'activity' => 'Shishito Peppers-Red Bags',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:25:27',
            ],
            [
                'cod_activity' => 54,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '21',
                'activity' => 'Peppers-Bulk',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:25:48',
            ],
            [
                'cod_activity' => 55,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '22',
                'activity' => 'Bell Peppers',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:26:11',
            ],
            [
                'cod_activity' => 56,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '23',
                'activity' => 'ECO Peppers',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:26:28',
            ],
            [
                'cod_activity' => 57,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '24',
                'activity' => 'Green Squash',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:26:49',
            ],
            [
                'cod_activity' => 58,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '25',
                'activity' => 'ECO Green Squash',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:27:05',
            ],
            [
                'cod_activity' => 59,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '26',
                'activity' => 'TJ\'S Green Squash',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:27:21',
            ],
            [
                'cod_activity' => 60,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '27',
                'activity' => 'Green Squash',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:27:36',
            ],
            [
                'cod_activity' => 61,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '28',
                'activity' => 'Cucumbers',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:27:51',
            ],
            [
                'cod_activity' => 62,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '29',
                'activity' => 'ECO Cucumbers',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-14 09:28:07',
            ],
            [
                'cod_activity' => 63,
                'cod_farms' => 1,
                'cod_location' => 1,
                'codigo' => '1',
                'activity' => 'Cleaning Ditches-Limpiando Canales',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-10-25 05:59:12',
            ],
            [
                'cod_activity' => 65,
                'cod_farms' => 2,
                'cod_location' => 4,
                'codigo' => '17',
                'activity' => 'Staking-Estaquiado',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-11-08 14:24:36',
            ],
            [
                'cod_activity' => 66,
                'cod_farms' => 2,
                'cod_location' => 4,
                'codigo' => '18',
                'activity' => 'Cleaning Ditches-Limpiando Canales',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-11-08 14:26:56',
            ],
            [
                'cod_activity' => 67,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '18',
                'activity' => 'ECO Jalapenos',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2024-11-13 07:55:49',
            ],
            [
                'cod_activity' => 68,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '30',
                'activity' => 'Romaine Hearts',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2025-01-14 06:25:48',
            ],
            [
                'cod_activity' => 69,
                'cod_farms' => 1,
                'cod_location' => 2,
                'codigo' => '40',
                'activity' => 'ECO Medley Mix',
                'piece_rate' => '0.01',
                'activo' => 1,
                'visible' => 1,
                'user_insert' => 3,
                'date_insert' => '2025-03-03 08:42:56',
            ],
        ]);

        DB::table('pay_actividades_por_dia')->insertOrIgnore([
            [
                'cod_actividad_por_dia' => 1,
                'actividad_por_dia' => 'Normal day',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-10-07 21:38:12',
            ],
            [
                'cod_actividad_por_dia' => 2,
                'actividad_por_dia' => 'Training',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-10-07 21:38:23',
            ],
            [
                'cod_actividad_por_dia' => 3,
                'actividad_por_dia' => 'Vacations',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2024-10-07 21:38:29',
            ],
        ]);

        Schema::enableForeignKeyConstraints();
    }
}
