<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class SystemCatalogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        DB::table('ug_info_sistema')->insertOrIgnore([
            [
                'cod_info_sistema' => 1,
                'nombre_sistema' => 'Lady Moon Farms',
                'descripcion_sistema' => 'Lion Farming',
                'logo_sistema' => '../libs/imgs/Lion Farming.png',
                'flag_mantenimiento' => 0,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2020-05-12 14:49:48',
            ],
        ]);

        DB::table('ug_unidades_medida')->insertOrIgnore([
            [
                'cod_unidad_medida' => 1,
                'unidad_medida' => 'Fluid Ounces',
                'abreviatura_medida' => 'Fl.Oz',
                'activo' => 0,
                'user_insert' => 1,
                'date_insert' => '2018-10-25 16:24:52',
            ],
            [
                'cod_unidad_medida' => 2,
                'unidad_medida' => 'Pounds',
                'abreviatura_medida' => 'Lb',
                'activo' => 0,
                'user_insert' => 1,
                'date_insert' => '2018-11-08 23:30:17',
            ],
            [
                'cod_unidad_medida' => 3,
                'unidad_medida' => 'Weight Ounces',
                'abreviatura_medida' => 'W.Oz',
                'activo' => 0,
                'user_insert' => 1,
                'date_insert' => '2018-11-08 23:30:27',
            ],
            [
                'cod_unidad_medida' => 4,
                'unidad_medida' => 'Pint',
                'abreviatura_medida' => 'Pnt',
                'activo' => 0,
                'user_insert' => 1,
                'date_insert' => '2018-11-08 23:30:38',
            ],
            [
                'cod_unidad_medida' => 5,
                'unidad_medida' => 'Meters',
                'abreviatura_medida' => 'Mts',
                'activo' => 0,
                'user_insert' => 1,
                'date_insert' => '2018-11-08 23:32:07',
            ],
            [
                'cod_unidad_medida' => 6,
                'unidad_medida' => 'Liters',
                'abreviatura_medida' => 'Lt',
                'activo' => 0,
                'user_insert' => 1,
                'date_insert' => '2018-11-09 14:40:31',
            ],
            [
                'cod_unidad_medida' => 7,
                'unidad_medida' => 'Gallons',
                'abreviatura_medida' => 'Gls',
                'activo' => 0,
                'user_insert' => 1,
                'date_insert' => '2018-11-09 14:40:40',
            ],
            [
                'cod_unidad_medida' => 8,
                'unidad_medida' => 'Tons',
                'abreviatura_medida' => 'Tn',
                'activo' => 0,
                'user_insert' => 1,
                'date_insert' => '2018-11-09 16:50:28',
            ],
            [
                'cod_unidad_medida' => 9,
                'unidad_medida' => 'Grams',
                'abreviatura_medida' => 'Gm',
                'activo' => 0,
                'user_insert' => 1,
                'date_insert' => '2019-01-01 23:26:24',
            ],
            [
                'cod_unidad_medida' => 10,
                'unidad_medida' => 'Quarts',
                'abreviatura_medida' => 'Qt',
                'activo' => 0,
                'user_insert' => 2,
                'date_insert' => '2019-01-07 15:25:17',
            ],
            [
                'cod_unidad_medida' => 11,
                'unidad_medida' => 'Bale',
                'abreviatura_medida' => 'Bl',
                'activo' => 0,
                'user_insert' => 3,
                'date_insert' => '2019-09-27 12:23:09',
            ],
            [
                'cod_unidad_medida' => 12,
                'unidad_medida' => 'Seed',
                'abreviatura_medida' => 'Sd',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2023-10-15 10:48:41',
            ],
            [
                'cod_unidad_medida' => 13,
                'unidad_medida' => 'Pounds',
                'abreviatura_medida' => 'Pd',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2023-12-07 17:07:49',
            ],
        ]);

        DB::table('ug_estados_ordenes_compra')->insertOrIgnore([
            [
                'cod_estado_orden_compra' => 1,
                'estado' => 'Saved',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2020-04-24 21:57:18',
            ],
            [
                'cod_estado_orden_compra' => 2,
                'estado' => 'Sent',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2020-04-24 21:57:19',
            ],
            [
                'cod_estado_orden_compra' => 3,
                'estado' => 'Received',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2020-04-24 21:57:19',
            ],
            [
                'cod_estado_orden_compra' => 4,
                'estado' => 'Canceled',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2020-05-05 22:31:25',
            ],
        ]);

        DB::table('ug_flujo_estados')->insertOrIgnore([
            [
                'cod_flujo' => 1,
                'cod_estado_actual' => 1,
                'cod_estado_ok' => 2,
                'cod_estado_cancel' => 9,
                'flag_flujo' => 1,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-28 13:30:33',
            ],
            [
                'cod_flujo' => 2,
                'cod_estado_actual' => 1,
                'cod_estado_ok' => 2,
                'cod_estado_cancel' => 9,
                'flag_flujo' => 0,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-28 13:30:33',
            ],
            [
                'cod_flujo' => 3,
                'cod_estado_actual' => 2,
                'cod_estado_ok' => 3,
                'cod_estado_cancel' => 9,
                'flag_flujo' => 1,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-28 13:30:34',
            ],
            [
                'cod_flujo' => 4,
                'cod_estado_actual' => 2,
                'cod_estado_ok' => 4,
                'cod_estado_cancel' => 9,
                'flag_flujo' => 0,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-28 13:30:34',
            ],
            [
                'cod_flujo' => 5,
                'cod_estado_actual' => 3,
                'cod_estado_ok' => 4,
                'cod_estado_cancel' => 9,
                'flag_flujo' => 1,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-28 13:30:34',
            ],
            [
                'cod_flujo' => 6,
                'cod_estado_actual' => 4,
                'cod_estado_ok' => 5,
                'cod_estado_cancel' => 9,
                'flag_flujo' => 1,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-28 13:30:34',
            ],
            [
                'cod_flujo' => 7,
                'cod_estado_actual' => 4,
                'cod_estado_ok' => 5,
                'cod_estado_cancel' => 9,
                'flag_flujo' => 0,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-28 13:30:34',
            ],
            [
                'cod_flujo' => 8,
                'cod_estado_actual' => 5,
                'cod_estado_ok' => 6,
                'cod_estado_cancel' => 9,
                'flag_flujo' => 1,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-28 13:30:34',
            ],
            [
                'cod_flujo' => 9,
                'cod_estado_actual' => 5,
                'cod_estado_ok' => 6,
                'cod_estado_cancel' => 9,
                'flag_flujo' => 0,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-28 13:30:35',
            ],
            [
                'cod_flujo' => 10,
                'cod_estado_actual' => 6,
                'cod_estado_ok' => 7,
                'cod_estado_cancel' => 9,
                'flag_flujo' => 1,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-28 13:30:35',
            ],
            [
                'cod_flujo' => 11,
                'cod_estado_actual' => 6,
                'cod_estado_ok' => 7,
                'cod_estado_cancel' => 9,
                'flag_flujo' => 0,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-28 13:30:35',
            ],
            [
                'cod_flujo' => 12,
                'cod_estado_actual' => 7,
                'cod_estado_ok' => 8,
                'cod_estado_cancel' => 9,
                'flag_flujo' => 1,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-28 13:30:35',
            ],
            [
                'cod_flujo' => 13,
                'cod_estado_actual' => 7,
                'cod_estado_ok' => 8,
                'cod_estado_cancel' => 9,
                'flag_flujo' => 0,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-28 13:30:35',
            ],
            [
                'cod_flujo' => 14,
                'cod_estado_actual' => 8,
                'cod_estado_ok' => 10,
                'cod_estado_cancel' => 9,
                'flag_flujo' => 1,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-28 13:30:35',
            ],
            [
                'cod_flujo' => 15,
                'cod_estado_actual' => 8,
                'cod_estado_ok' => 10,
                'cod_estado_cancel' => 9,
                'flag_flujo' => 0,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-28 13:30:36',
            ],
            [
                'cod_flujo' => 16,
                'cod_estado_actual' => 3,
                'cod_estado_ok' => 4,
                'cod_estado_cancel' => 9,
                'flag_flujo' => 0,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-28 13:30:34',
            ],
        ]);

        DB::table('ug_formularios_estados')->insertOrIgnore([
            [
                'cod_estado' => 1,
                'nombre_estado' => 'Testing',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2019-12-13 23:22:57',
            ],
            [
                'cod_estado' => 2,
                'nombre_estado' => 'Review',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2019-12-13 23:22:57',
            ],
            [
                'cod_estado' => 3,
                'nombre_estado' => 'Canceled',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2019-12-13 23:22:58',
            ],
        ]);

        DB::table('ug_formularios_tipo_items')->insertOrIgnore([
            [
                'cod_tipo_item' => 1,
                'tipo_item' => 'Checkbox',
                'max_opciones' => 1,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-10-25 19:11:17',
            ],
            [
                'cod_tipo_item' => 2,
                'tipo_item' => 'Textbox Double',
                'max_opciones' => 2,
                'activo' => 0,
                'user_insert' => 1,
                'date_insert' => '2018-10-25 19:11:17',
            ],
            [
                'cod_tipo_item' => 3,
                'tipo_item' => 'Selectpicker',
                'max_opciones' => 10,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-10-25 19:11:17',
            ],
            [
                'cod_tipo_item' => 4,
                'tipo_item' => 'Attached',
                'max_opciones' => 1,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-12 11:41:31',
            ],
            [
                'cod_tipo_item' => 5,
                'tipo_item' => 'Textbox Simple',
                'max_opciones' => 1,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2019-01-14 22:46:42',
            ],
            [
                'cod_tipo_item' => 6,
                'tipo_item' => 'Date',
                'max_opciones' => 1,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2019-01-14 22:46:42',
            ],
            [
                'cod_tipo_item' => 7,
                'tipo_item' => 'Textarea',
                'max_opciones' => 1,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2019-12-10 21:24:44',
            ],
            [
                'cod_tipo_item' => 8,
                'tipo_item' => 'Selectpicker with dependent',
                'max_opciones' => 5,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2019-12-10 21:24:44',
            ],
            [
                'cod_tipo_item' => 9,
                'tipo_item' => 'Radio Button',
                'max_opciones' => 3,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2019-12-10 21:24:44',
            ],
            [
                'cod_tipo_item' => 10,
                'tipo_item' => 'Min - Max Textbox',
                'max_opciones' => 2,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2020-01-13 16:24:18',
            ],
            [
                'cod_tipo_item' => 11,
                'tipo_item' => 'Time',
                'max_opciones' => 1,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2020-01-22 11:34:27',
            ],
        ]);

        DB::table('ug_tipo_noticias')->insertOrIgnore([
            [
                'cod_tipo_noticia' => 1,
                'tipo_noticia' => 'News - Noticia',
                'clase' => 'event-success',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2020-02-10 16:58:46',
            ],
            [
                'cod_tipo_noticia' => 2,
                'tipo_noticia' => 'Event - Evento',
                'clase' => 'event-special',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2020-02-10 16:58:46',
            ],
            [
                'cod_tipo_noticia' => 3,
                'tipo_noticia' => 'Notice - Aviso',
                'clase' => 'event-info',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2020-02-10 16:58:46',
            ],
            [
                'cod_tipo_noticia' => 4,
                'tipo_noticia' => 'Urgent - Urgente',
                'clase' => 'event-important',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2020-02-10 16:58:46',
            ],
            [
                'cod_tipo_noticia' => 5,
                'tipo_noticia' => 'Urgente',
                'clase' => 'event-inverse',
                'activo' => 0,
                'user_insert' => 1,
                'date_insert' => '2014-10-15 15:15:37',
            ],
        ]);

        DB::table('bw_estados_plantacion')->insertOrIgnore([
            [
                'cod_estado_plantacion' => 1,
                'cod_estado_padre' => NULL,
                'estado_plantacion' => 'Guardada',
                'estado_plantacion_english' => 'Pre-Planting',
                'tiempo_espera' => 0,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-24 00:03:06',
            ],
            [
                'cod_estado_plantacion' => 2,
                'cod_estado_padre' => NULL,
                'estado_plantacion' => 'Plantado',
                'estado_plantacion_english' => 'Planted',
                'tiempo_espera' => 72,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-10-23 22:34:46',
            ],
            [
                'cod_estado_plantacion' => 3,
                'cod_estado_padre' => NULL,
                'estado_plantacion' => 'Poda',
                'estado_plantacion_english' => 'Trimmed',
                'tiempo_espera' => 72,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-10-25 16:50:40',
            ],
            [
                'cod_estado_plantacion' => 4,
                'cod_estado_padre' => NULL,
                'estado_plantacion' => 'Crecimiento',
                'estado_plantacion_english' => 'Growing',
                'tiempo_espera' => 720,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-10-23 22:34:47',
            ],
            [
                'cod_estado_plantacion' => 5,
                'cod_estado_padre' => NULL,
                'estado_plantacion' => 'Listo para cosechar',
                'estado_plantacion_english' => 'Ready to harvest',
                'tiempo_espera' => 48,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-10-23 22:34:47',
            ],
            [
                'cod_estado_plantacion' => 6,
                'cod_estado_padre' => NULL,
                'estado_plantacion' => 'Cosechado',
                'estado_plantacion_english' => 'Harvested',
                'tiempo_espera' => 72,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-10-23 22:34:47',
            ],
            [
                'cod_estado_plantacion' => 7,
                'cod_estado_padre' => NULL,
                'estado_plantacion' => 'Control de calidad',
                'estado_plantacion_english' => 'QA',
                'tiempo_espera' => 42,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-10-23 22:34:48',
            ],
            [
                'cod_estado_plantacion' => 8,
                'cod_estado_padre' => NULL,
                'estado_plantacion' => 'Producto empacado',
                'estado_plantacion_english' => 'Packaged product',
                'tiempo_espera' => 72,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-10-23 22:34:48',
            ],
            [
                'cod_estado_plantacion' => 9,
                'cod_estado_padre' => NULL,
                'estado_plantacion' => 'Eliminado',
                'estado_plantacion_english' => 'Removed',
                'tiempo_espera' => 0,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-10-23 22:34:48',
            ],
            [
                'cod_estado_plantacion' => 10,
                'cod_estado_padre' => NULL,
                'estado_plantacion' => 'Terminado',
                'estado_plantacion_english' => 'Finished',
                'tiempo_espera' => 0,
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-10-25 17:07:11',
            ],
        ]);

        DB::table('bw_inventario_estados_plantaciones')->insertOrIgnore([
            [
                'cod_estado' => 1,
                'nombre' => 'Georgia ',
                'abreviatura' => 'GA',
                'descripcion' => NULL,
                'activo' => 1,
                'user_insert' => 73,
                'date_insert' => '2023-09-29 06:34:37',
            ],
            [
                'cod_estado' => 2,
                'nombre' => 'Florida',
                'abreviatura' => 'FL',
                'descripcion' => NULL,
                'activo' => 1,
                'user_insert' => 73,
                'date_insert' => '2023-09-29 06:34:37',
            ],
            [
                'cod_estado' => 3,
                'nombre' => 'Pennsylvania',
                'abreviatura' => 'PA',
                'descripcion' => NULL,
                'activo' => 1,
                'user_insert' => 73,
                'date_insert' => '2023-09-29 06:34:38',
            ],
        ]);

        DB::table('bw_inventario_tipo_semillas')->insertOrIgnore([
            [
                'cod_tipo_semilla' => 1,
                'tipo_semilla' => 'Organic',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2023-11-04 09:26:06',
            ],
            [
                'cod_tipo_semilla' => 2,
                'tipo_semilla' => 'Not Treated',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2023-11-04 09:26:07',
            ],
        ]);

        DB::table('bw_tipo_quimico')->insertOrIgnore([
            [
                'cod_tipo_quimico' => 1,
                'tipo_quimico' => 'Herbicide',
                'activo' => 1,
                'user_insert' => 2,
                'date_insert' => '2019-01-07 14:26:44',
            ],
            [
                'cod_tipo_quimico' => 2,
                'tipo_quimico' => 'Fungicide',
                'activo' => 1,
                'user_insert' => 2,
                'date_insert' => '2019-01-07 14:26:59',
            ],
            [
                'cod_tipo_quimico' => 3,
                'tipo_quimico' => 'Insecticide',
                'activo' => 1,
                'user_insert' => 2,
                'date_insert' => '2019-01-07 14:27:14',
            ],
            [
                'cod_tipo_quimico' => 4,
                'tipo_quimico' => 'Dry Fertilizer',
                'activo' => 1,
                'user_insert' => 2,
                'date_insert' => '2019-01-07 14:27:30',
            ],
            [
                'cod_tipo_quimico' => 5,
                'tipo_quimico' => 'Foliar Fertilizer',
                'activo' => 1,
                'user_insert' => 2,
                'date_insert' => '2019-01-07 14:27:45',
            ],
            [
                'cod_tipo_quimico' => 6,
                'tipo_quimico' => 'Adjuvant',
                'activo' => 1,
                'user_insert' => 2,
                'date_insert' => '2019-01-07 14:28:01',
            ],
            [
                'cod_tipo_quimico' => 7,
                'tipo_quimico' => 'Liquid Fertilizer',
                'activo' => 1,
                'user_insert' => 2,
                'date_insert' => '2019-01-07 16:04:30',
            ],
            [
                'cod_tipo_quimico' => 8,
                'tipo_quimico' => 'Buffer',
                'activo' => 1,
                'user_insert' => 2,
                'date_insert' => '2019-01-07 16:12:28',
            ],
            [
                'cod_tipo_quimico' => 9,
                'tipo_quimico' => 'Dry fertilizer',
                'activo' => 1,
                'user_insert' => 16,
                'date_insert' => '2022-12-22 07:35:24',
            ],
            [
                'cod_tipo_quimico' => 10,
                'tipo_quimico' => 'Alias 4F',
                'activo' => 0,
                'user_insert' => 75,
                'date_insert' => '2023-01-24 11:01:12',
            ],
        ]);

        DB::table('bw_tipo_temporada')->insertOrIgnore([
            [
                'cod_tipo_temporada' => 1,
                'tipo_temporada' => 'On Season',
                'activo' => 1,
                'user_insert' => 2,
                'date_insert' => '2019-01-07 10:07:25',
            ],
            [
                'cod_tipo_temporada' => 2,
                'tipo_temporada' => 'Off Season',
                'activo' => 1,
                'user_insert' => 2,
                'date_insert' => '2019-01-07 10:07:39',
            ],
            [
                'cod_tipo_temporada' => 3,
                'tipo_temporada' => 'On Season-Water Spinach',
                'activo' => 1,
                'user_insert' => 75,
                'date_insert' => '2022-08-04 10:34:53',
            ],
        ]);

        DB::table('bw_tipos_periodos')->insertOrIgnore([
            [
                'cod_tipo_periodo' => 1,
                'tipo_periodo' => 'Days',
                'activo' => 1,
                'user_insert' => 2,
                'date_insert' => '2019-01-07 14:29:54',
            ],
            [
                'cod_tipo_periodo' => 2,
                'tipo_periodo' => 'Hours',
                'activo' => 1,
                'user_insert' => 2,
                'date_insert' => '2019-01-07 14:50:39',
            ],
        ]);

        DB::table('bw_tipos_items')->insertOrIgnore([
            [
                'cod_tipo_item' => 1,
                'tipo_item' => 'Checkbox',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-10-25 19:11:17',
            ],
            [
                'cod_tipo_item' => 2,
                'tipo_item' => 'Textbox Doble',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-10-25 19:11:17',
            ],
            [
                'cod_tipo_item' => 3,
                'tipo_item' => 'Selectpicker',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-10-25 19:11:17',
            ],
            [
                'cod_tipo_item' => 4,
                'tipo_item' => 'Adjunto - Attached',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-11-12 11:41:31',
            ],
            [
                'cod_tipo_item' => 5,
                'tipo_item' => 'Textbox Simple',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2019-01-14 22:46:42',
            ],
            [
                'cod_tipo_item' => 6,
                'tipo_item' => 'Fecha - Date',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2019-01-14 22:46:42',
            ],
        ]);

        DB::table('bw_tipo_aplicacion_maquinaria')->insertOrIgnore([
            [
                'cod_tipo_aplicacion' => 1,
                'tipo_aplicacion' => 'Broadcast',
                'activo' => 1,
                'user_insert' => 2,
                'date_insert' => '2019-01-07 14:30:22',
            ],
            [
                'cod_tipo_aplicacion' => 2,
                'tipo_aplicacion' => 'Chemigation',
                'activo' => 1,
                'user_insert' => 2,
                'date_insert' => '2019-01-07 14:31:06',
            ],
            [
                'cod_tipo_aplicacion' => 3,
                'tipo_aplicacion' => 'Air Blast',
                'activo' => 1,
                'user_insert' => 2,
                'date_insert' => '2019-01-07 14:31:25',
            ],
            [
                'cod_tipo_aplicacion' => 4,
                'tipo_aplicacion' => 'Planting Machinery',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2019-01-15 10:43:29',
            ],
            [
                'cod_tipo_aplicacion' => 5,
                'tipo_aplicacion' => 'Apply by Hand',
                'activo' => 1,
                'user_insert' => 2,
                'date_insert' => '2019-02-13 10:13:26',
            ],
        ]);

        DB::table('bw_tipo_zona_rociado')->insertOrIgnore([
            [
                'cod_tipo_zona' => 1,
                'tipo_zona' => 'Ditches',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2019-08-19 23:03:48',
            ],
            [
                'cod_tipo_zona' => 2,
                'tipo_zona' => 'Canals',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2019-08-19 23:03:48',
            ],
            [
                'cod_tipo_zona' => 3,
                'tipo_zona' => 'Sprinkle Rows',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2019-08-19 23:03:49',
            ],
            [
                'cod_tipo_zona' => 4,
                'tipo_zona' => 'Beds',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2019-08-25 14:08:16',
            ],
            [
                'cod_tipo_zona' => 5,
                'tipo_zona' => 'Spots',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2019-08-25 14:08:17',
            ],
            [
                'cod_tipo_zona' => 6,
                'tipo_zona' => 'Grass Outside Production Area',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2020-05-06 06:53:03',
            ],
            [
                'cod_tipo_zona' => 7,
                'tipo_zona' => 'Edges',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2020-05-21 12:45:26',
            ],
        ]);

        DB::table('bw_sembradores')->insertOrIgnore([
            [
                'cod_sembrador' => 1,
                'nombre_contacto' => 'Speedling',
                'correo_contacto' => 'BarkerJ@helenaagri.com',
                'telefono_contacto' => '(772) 464-8660',
                'observaciones' => 'Warehouse Manager',
                'activo' => 1,
                'user_insert' => 73,
                'date_insert' => '2023-09-21 12:57:14',
            ],
            [
                'cod_sembrador' => 2,
                'nombre_contacto' => 'Barnet',
                'correo_contacto' => 'Barnet@mail.com',
                'telefono_contacto' => '(772) 464-0111',
                'observaciones' => 'Warehouse Manager',
                'activo' => 1,
                'user_insert' => 73,
                'date_insert' => '2023-09-21 12:57:14',
            ],
            [
                'cod_sembrador' => 3,
                'nombre_contacto' => 'Faye Rogers',
                'correo_contacto' => 'frogers79@comcast.net',
                'telefono_contacto' => '(772) 260-0718',
                'observaciones' => 'Sales Manager',
                'activo' => 0,
                'user_insert' => 73,
                'date_insert' => '2023-09-21 12:57:14',
            ],
        ]);

        DB::table('bw_info_empresa')->insertOrIgnore([
            [
                'cod_info_empresa' => 31,
                'cod_gerencia' => 10,
                'nombre_empresa' => 'Speedling',
                'lema_empresa' => 'Speedling',
                'direccion_linea_1' => '47270 Bermont Rd',
                'direccion_linea_2' => NULL,
                'telefono_empresa' => '(239) 462-6276',
                'correo_empresa' => 'anais@ladymoonfarms.com',
                'fax_empresa' => NULL,
                'descripcion_empresa' => NULL,
                'logo_empresa' => 'logo_empresa_1.jpeg',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-10-25 11:21:20',
            ],
            [
                'cod_info_empresa' => 32,
                'cod_gerencia' => 10,
                'nombre_empresa' => 'Barnett',
                'lema_empresa' => 'Barnett',
                'direccion_linea_1' => '47270 Bermont Rd',
                'direccion_linea_2' => NULL,
                'telefono_empresa' => '(239) 462-6276',
                'correo_empresa' => 'anais@ladymoonfarms.com',
                'fax_empresa' => NULL,
                'descripcion_empresa' => NULL,
                'logo_empresa' => 'logo_empresa_1.jpeg',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2018-10-25 11:21:20',
            ],
            [
                'cod_info_empresa' => 33,
                'cod_gerencia' => 10,
                'nombre_empresa' => 'Mobley Greenhouse',
                'lema_empresa' => 'Mobley Greenhouse',
                'direccion_linea_1' => '1351 W Cowboy Way, LaBelle, FL 33935',
                'direccion_linea_2' => NULL,
                'telefono_empresa' => '(863) 675-2020',
                'correo_empresa' => 'carol@mobleyplantworld.com',
                'fax_empresa' => NULL,
                'descripcion_empresa' => NULL,
                'logo_empresa' => NULL,
                'activo' => 1,
                'user_insert' => 2,
                'date_insert' => '2023-11-27 14:02:24',
            ],
            [
                'cod_info_empresa' => 34,
                'cod_gerencia' => 10,
                'nombre_empresa' => 'PA Greenhouse',
                'lema_empresa' => NULL,
                'direccion_linea_1' => '1795 Criders Church Rd, Chambersburg, PA 17202',
                'direccion_linea_2' => NULL,
                'telefono_empresa' => '(717) 369-2113',
                'correo_empresa' => 'anais@ladymoonfarms.com',
                'fax_empresa' => '() -',
                'descripcion_empresa' => 'PA Greenhouse owned by LMF',
                'logo_empresa' => NULL,
                'activo' => 1,
                'user_insert' => 2,
                'date_insert' => '2024-05-01 13:40:13',
            ],
        ]);

        DB::table('doc_tipo_documentos')->insertOrIgnore([
            [
                'cod_tipo_documento' => 1,
                'tipo_documento' => 'Manual',
                'descripcion' => 'Description here',
                'color_tipo' => '#009900',
                'activo' => 1,
                'user_insert' => 1,
                'date_insert' => '2019-10-15 23:50:49',
            ],
        ]);

        DB::table('qua_productos')->insertOrIgnore([
            [
                'cod_producto' => 1,
                'nombre_producto' => 'Arugula',
                'cod_pais' => 840,
                'cod_departamento' => 10,
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2019-08-12 06:35:06',
            ],
            [
                'cod_producto' => 2,
                'nombre_producto' => 'Red Kale',
                'cod_pais' => 840,
                'cod_departamento' => 10,
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2019-08-12 06:35:26',
            ],
            [
                'cod_producto' => 3,
                'nombre_producto' => 'Spinach',
                'cod_pais' => 840,
                'cod_departamento' => 10,
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2019-08-12 06:36:14',
            ],
            [
                'cod_producto' => 4,
                'nombre_producto' => 'Land Cress',
                'cod_pais' => 840,
                'cod_departamento' => 10,
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2019-08-12 06:36:41',
            ],
            [
                'cod_producto' => 5,
                'nombre_producto' => 'Red Lettuce',
                'cod_pais' => 840,
                'cod_departamento' => 10,
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2020-09-17 20:48:28',
            ],
            [
                'cod_producto' => 6,
                'nombre_producto' => 'Green Leaf Lettuce',
                'cod_pais' => 840,
                'cod_departamento' => 10,
                'activo' => 1,
                'user_insert' => 3,
                'date_insert' => '2020-09-17 20:48:49',
            ],
        ]);

        Schema::enableForeignKeyConstraints();
    }
}
